---
contentdir: "content"
layoutdir: "themes/Lanyon/layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://ChrisPC.github.io"
title: "Novel Interaction"
canonifyurls: true
theme: "Lanyon"
...